Repository cdnjs/new-website, pull requests merged in 2019-11, with the labels that each got.

#199 [Website] Add last modified header
  webServer.js
Labels: ✳️ enhancement

#303 [Website] Fix copy button padding
  public/css/main.css
Labels: ✳️ enhancement, 🖥 page design

#306 [API] Clean all fields to prevent XSS
  apiServer.js
Labels: ‼️ priority, 📡 api, 🔐 security issue

#300 [Tests] Add object-curly-spacing rule to ESLint
  .eslintrc.json
Labels: ‼️ priority, 🧪 tests

#304 [Website] Fix #277: Integrated library name and description in one clickable div
  public/css/main.css
  public/js/main.js
Labels: 🖥 page design

#268 [Website] Update brand images & meta tags
  public/img/cdnjs-banner.png
  public/img/cdnjs-icon.png
  templates/layout.html
Labels: ✳️ enhancement, 🖥 page design

#307 [Tests] Explicit length comparison
  .eslintrc.json
  apiServer.js
  package.json
Labels: 🧪 tests

#302 [Tests] Add stylelint for public/css/*.css
  .stylelintrc
  package.json
  public/css/main.css
  public/css/theme.css
Labels: ‼️ priority, 🧪 tests
