Repository cdnjs/new-website, pull requests merged in 2020-01, with the labels that each got.

#296 [Tests] Add HTML linting (html-validate & linthtml)
  .htmlvalidate.json
  .linthtmlrc.json
  package.json
  public/css/main.css
  public/js/main.js
  templates/about.html
  templates/api.html
  templates/home.html
  templates/layout.html
  templates/libraries.html
  templates/library.html
  templates/login.html
  templates/members.html
  templates/news.html
  templates/newsfeed.html
  templates/newsfeed_item.html
  templates/profile.html
  templates/register.html
  templates/tutorial.html
  update.js
  webServer.js
Labels: ‼️ priority, 🧪 tests

#301 [Website] Lint & refactor public/js/*.js
  package.json
  public/js/main.js
Labels: ‼️ priority, 🧪 tests

#266 [Website] Fix GitHub banner & homepage responsiveness
  public/css/main.css
  public/css/theme.css
  public/js/main.js
  templates/layout.html
Labels: ‼️ priority, ✳️ enhancement, 📱 responsiveness

#267 [Website] Implement breadcrumb on all pages following Schema spec
  public/css/theme.css
  templates/about.html
  templates/api.html
  templates/breadcrumbs.html
  templates/home.html
  templates/layout.html
  templates/libraries.html
  templates/library.html
  templates/tutorial.html
  templates/tutorials.html
  webServer.js
Labels: ✳️ enhancement, 🖇 navigation, 🖥 page design

#265 [Website] Highlight the default file in the library view
  public/css/theme.css
  templates/library.html
  webServer.js
Labels: ✳️ enhancement, 🖥 page design

#246 [API] SRI data in API
  apiServer.js
  templates/api.html
Labels: ✳️ enhancement, 📡 api

#204 [Website] Display library assets only important files
  package.json
  public/js/main.js
  templates/library.html
  webServer.js
Labels: ✳️ enhancement

#169 Display library assets by type
  public/css/main.css
  public/css/theme.css
  public/js/main.js
  templates/layout.html
  templates/libraries.html
  templates/library.html
  webServer.js
Labels: ‼️ priority, ✳️ enhancement
